[docs] Add HGV time restrictions
tilezen/vector-datasource pull request #1948
Opened 2021-03-24 16:53 UTC by rinnyB

Hi.
This pull request is to add Heavy Good Vehicle time restrictions.
Restrictions may include the date, day, time, or other time range when a specific restriction is enabled.

This is a follow-up on https://github.com/tilezen/vector-datasource/pull/1846

2021-04-05 22:57 UTC, nvkelso reviewed
Generally this looks fine to me... but I'm curious are `seconds` the right measurement here instead of `minutes`?

2021-04-05 22:59 UTC, nvkelso commented on docs/layers.md
> +* `days_of_month` - range of days of month, for example, `days_of_month 1-10`
There can be 31 days in a month, so a better example `days_of_month 1-31`?

2021-04-05 22:59 UTC, nvkelso commented on docs/layers.md
> +* `day_week_month` - range of days of week of month, for example, `day_week_month Mon1-Sat3`
I don't understand what `Mon1-Sat3` means, can you extend the example with more words please?

2021-04-05 23:00 UTC, nvkelso commented on docs/layers.md
> +* `day_week_year` - range of days of week of year, for example, `day_week_year Wed12-Fri36`
I don't understand what `Wed12-Fri36` means, can you extend the example with more words, please?

2021-04-05 23:01 UTC, nvkelso commented on docs/layers.md
> +* `week_of_month` - range of weeks of month, for example, `week_of_month 1-4`
Sometimes there can be 5 weeks in a month?

2021-04-05 23:02 UTC, nvkelso commented on docs/layers.md
> +Time restriction is a semicolon-delimited array of date and time restrictions,
We should say in English names for days and months?

2021-04-05 23:02 UTC, nvkelso commented on docs/layers.md
> +* `day_week_month_year` - range of days of weeks of months of year, for example, `day_week_month_year JulSun1-DecMon1`
I don't understand what `JulSun1-DecMon1` means, can you extend the example with more words, please?

2021-04-05 23:03 UTC, nvkelso commented on docs/layers.md
> +* `externally_specified` - externally specified string value, for example, `externally_specified <string-value>`
You mean this is a link to a web address or raw text or?

2021-04-05 23:03 UTC, nvkelso requested changes
Please address comments.

2021-04-26 15:07 UTC, rinnyB commented
> Please address comments.

Hello, @nvkelso,
thank you for the review and sorry for the delayed response.
I've expanded the examples a bit.

2021-04-27 23:15 UTC, nvkelso commented on docs/layers.md
> +* `externally_specified` - externally specified string value, for example, `externally_specified <string-value>`
@rinnyB can you resolve this one and then the PR will be in mergable state, please?

2021-04-27 23:15 UTC, nvkelso commented
@rinnyB I'm still unclear on what `externally_specified` is used for. Can you elaborate on that and then I'll merge the PR?

2021-06-16 04:59 UTC, nvkelso commented
Change looks good to me, thanks!

2021-06-16 04:59 UTC, merged