Chinese paser for OSM
tilezen/vector-datasource pull request #1956
Opened 2021-06-14 23:39 UTC by peitili

- [ ] Update tests
- [ ] Update docs

2021-06-15 20:40 UTC, travisgrigsby approved these changes
nice - I'm assuming you'll add two more for the other two data sources in a followup.  Nice work with the tests exactly laying out how your code works

2021-06-15 20:40 UTC, travisgrigsby commented on vectordatasource/transform.py
> +    """ First check whether name:zh (Simplified) and name:zht(Traditional)
great comment

2021-06-15 20:51 UTC, iandees approved these changes

2021-06-15 22:21 UTC, nvkelso commented on integration-test/1955-chinese-parser.py
> +             'name:zht': '舊金山'})
Can you also add another assert for this same tile, same place ID that `name:zh-default` is NOT exported in tiles, please?

2021-06-15 22:22 UTC, nvkelso reviewed
One nit to address to make sure intermediate processing data is not exported into tiles (it's been an issue in the past we should always guard against).

2021-06-15 22:26 UTC, peitili commented
> One nit to address to make sure intermediate processing data is not exported into tiles (it's been an issue in the past we should always guard against).

ok, I will remove the zh-default prop

2021-06-15 22:28 UTC, nvkelso requested changes
For the `docs` checkmark, thanks for updating the TESTS.md, but please also update 

https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#name-localization

With a note about `name:zh` (Simplified Chinese characters as used in China and Singapore) and `name:zht` for (Traditional Chinese characters used in Taiwan, Hong Kong, Macau) and how the data value backfilling works, and that we don't auto-translate to simplified <> traditional.

2021-06-15 22:36 UTC, peitili commented
> For the `docs` checkmark, thanks for updating the TESTS.md, but please also update
> 
> https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#name-localization
> 
> With a note about `name:zh` (Simplified Chinese characters as used in China and Singapore) and `name:zht` for (Traditional Chinese characters used in Taiwan, Hong Kong, Macau) and how the data value backfilling works, and that we don't auto-translate to simplified <> traditional.


sure, do we also need to change CHANGELOG and VERSION stuffs or shall we wait until NatualEarth and WOF parser are done too?

2021-06-15 23:21 UTC, peitili commented
> For the `docs` checkmark, thanks for updating the TESTS.md, but please also update
> 
> https://github.com/tilezen/vector-datasource/blob/master/docs/layers.md#name-localization
> 
> With a note about `name:zh` (Simplified Chinese characters as used in China and Singapore) and `name:zht` for (Traditional Chinese characters used in Taiwan, Hong Kong, Macau) and how the data value backfilling works, and that we don't auto-translate to simplified <> traditional.

fixed

2021-06-16 00:34 UTC, nvkelso commented on docs/layers.md
> +Both `name:zh` and `name:zht` properties are best-effort. It means `name:zh` can sometimes contain Traditional Chinese and `name:zht` can sometimes contain Simplified Chinese. And we don't auto-trans
Nit: add extra line between the header and the paragraph text to match the Markdown formatting used in this doc.

2021-06-16 00:35 UTC, nvkelso commented on docs/layers.md
> +We use three fields `name:zh`, `name:zh-Hans` and `name:zh-Hant` from OSM to populate two properties:
Nit: add extra line between the header and the paragraph text to match the Markdown formatting used in this doc.

2021-06-16 00:35 UTC, nvkelso commented on integration-test/1955-chinese-parser.py
> +        self.assert_no_matching_feature(16, 10482, 25330, 'places', {'name:zh-default': u'旧金山/三藩市/舊金山'})
Nit: Please format this onto multiple lines like the other assert for legibility / convention.

2021-06-16 00:36 UTC, nvkelso approved these changes
Great inaugural PR, thank you!

The documentation changes work for me, though please address the 3 nits comments I left (all formatting) before merging the PR.

2021-06-16 01:21 UTC, nvkelso commented on docs/TESTS.md
> +In your virtual environment of this repo run the following commands to install dependencies
Nit: add another line here between header and paragraph text

2021-06-16 04:49 UTC, merged